<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="59" passed="8" failed="44" skipped="7">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-08-10T20:07:46 TRT" name="Player Controller Test Suite" finished-at="2025-08-10T20:08:29 TRT" duration-ms="43335">
    <groups>
    </groups>
    <test started-at="2025-08-10T20:07:46 TRT" name="Player Controller Tests" finished-at="2025-08-10T20:08:29 TRT" duration-ms="43335">
      <class name="api.PlayerDeleteTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:00 TRT" name="setUp" finished-at="2025-08-10T20:08:00 TRT" duration-ms="206" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testAdminCanDeleteOtherUsers()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:00 TRT" name="testAdminCanDeleteOtherUsers" description="Admin can delete other users" finished-at="2025-08-10T20:08:00 TRT" duration-ms="178" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected status code 404 for not found user. expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected status code 404 for not found user. expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerDeleteTest.verifyPlayerDeletion(PlayerDeleteTest.java:201)
at api.PlayerDeleteTest.testAdminCanDeleteOtherUsers(PlayerDeleteTest.java:161)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAdminCanDeleteOtherUsers -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:00 TRT" name="tearDown" finished-at="2025-08-10T20:08:00 TRT" duration-ms="355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:01 TRT" name="setUp" finished-at="2025-08-10T20:08:01 TRT" duration-ms="173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testDeleteAdminByAdmin()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:01 TRT" name="testDeleteAdminByAdmin" description="Delete admin by admin (self-deletion)" finished-at="2025-08-10T20:08:01 TRT" duration-ms="96" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status code should be 403 when admin tries to delete himself expected [403] but found [204]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status code should be 403 when admin tries to delete himself expected [403] but found [204]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerDeleteTest.testDeleteAdminByAdmin(PlayerDeleteTest.java:130)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteAdminByAdmin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:01 TRT" name="tearDown" finished-at="2025-08-10T20:08:01 TRT" duration-ms="347" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:01 TRT" name="setUp" finished-at="2025-08-10T20:08:01 TRT" duration-ms="163" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testDeleteAdminBySupervisor()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:01 TRT" name="testDeleteAdminBySupervisor" description="Delete admin by supervisor" finished-at="2025-08-10T20:08:01 TRT" duration-ms="165" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected status code 404 for not found user. expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected status code 404 for not found user. expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerDeleteTest.verifyPlayerDeletion(PlayerDeleteTest.java:201)
at api.PlayerDeleteTest.testDeleteAdminBySupervisor(PlayerDeleteTest.java:95)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteAdminBySupervisor -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:01 TRT" name="tearDown" finished-at="2025-08-10T20:08:02 TRT" duration-ms="349" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:02 TRT" name="setUp" finished-at="2025-08-10T20:08:02 TRT" duration-ms="179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testDeleteNonExistentPlayer()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:02 TRT" name="testDeleteNonExistentPlayer" description="Delete non-existent player" finished-at="2025-08-10T20:08:02 TRT" duration-ms="91" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status code should be 404 when deleting non-existent player expected [404] but found [403]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status code should be 404 when deleting non-existent player expected [404] but found [403]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerDeleteTest.testDeleteNonExistentPlayer(PlayerDeleteTest.java:104)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteNonExistentPlayer -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:02 TRT" name="tearDown" finished-at="2025-08-10T20:08:02 TRT" duration-ms="342" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:02 TRT" name="setUp" finished-at="2025-08-10T20:08:03 TRT" duration-ms="187" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testDeletePlayerWithAdmin()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:03 TRT" name="testDeletePlayerWithAdmin" description="Delete player with admin" finished-at="2025-08-10T20:08:03 TRT" duration-ms="169" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected status code 404 for not found user. expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected status code 404 for not found user. expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerDeleteTest.verifyPlayerDeletion(PlayerDeleteTest.java:201)
at api.PlayerDeleteTest.testDeletePlayerWithAdmin(PlayerDeleteTest.java:83)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeletePlayerWithAdmin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:03 TRT" name="tearDown" finished-at="2025-08-10T20:08:03 TRT" duration-ms="330" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:03 TRT" name="setUp" finished-at="2025-08-10T20:08:03 TRT" duration-ms="173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testDeletePlayerWithBoundaryIds()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:03 TRT" name="testDeletePlayerWithBoundaryIds" description="Delete player with boundary ID values" finished-at="2025-08-10T20:08:03 TRT" duration-ms="87" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status code should be 404 when deleting player with very large ID expected [400] but found [403]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status code should be 404 when deleting player with very large ID expected [400] but found [403]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerDeleteTest.testDeletePlayerWithBoundaryIds(PlayerDeleteTest.java:171)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeletePlayerWithBoundaryIds -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:03 TRT" name="tearDown" finished-at="2025-08-10T20:08:04 TRT" duration-ms="362" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:04 TRT" name="setUp" finished-at="2025-08-10T20:08:04 TRT" duration-ms="212" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testDeletePlayerWithNonExistentEditor()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:04 TRT" name="testDeletePlayerWithNonExistentEditor" description="Delete player with non-existent editor" finished-at="2025-08-10T20:08:04 TRT" duration-ms="116" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status code should be 403 when deleting with non-existent editor expected [403] but found [204]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status code should be 403 when deleting with non-existent editor expected [403] but found [204]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerDeleteTest.testDeletePlayerWithNonExistentEditor(PlayerDeleteTest.java:112)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeletePlayerWithNonExistentEditor -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:04 TRT" name="tearDown" finished-at="2025-08-10T20:08:05 TRT" duration-ms="381" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:05 TRT" name="setUp" finished-at="2025-08-10T20:08:05 TRT" duration-ms="85" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 200, but was 400 expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 200, but was 400 expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerDeleteTest.createAndVerifyPlayer(PlayerDeleteTest.java:185)
at api.PlayerDeleteTest.setUp(PlayerDeleteTest.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:578)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testDeletePlayerWithSupervisor()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:05 TRT" name="testDeletePlayerWithSupervisor" description="Delete player with supervisor" finished-at="2025-08-10T20:08:05 TRT" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 200, but was 400 expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 200, but was 400 expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerDeleteTest.createAndVerifyPlayer(PlayerDeleteTest.java:185)
at api.PlayerDeleteTest.setUp(PlayerDeleteTest.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:578)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeletePlayerWithSupervisor -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:05 TRT" name="tearDown" finished-at="2025-08-10T20:08:05 TRT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:05 TRT" name="setUp" finished-at="2025-08-10T20:08:05 TRT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testDeleteSupervisor()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:05 TRT" name="testDeleteSupervisor" description="Delete supervisor (should be forbidden)" finished-at="2025-08-10T20:08:05 TRT" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 200, but was 400 expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 200, but was 400 expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerDeleteTest.createAndVerifyPlayer(PlayerDeleteTest.java:185)
at api.PlayerDeleteTest.setUp(PlayerDeleteTest.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:578)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteSupervisor -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:05 TRT" name="tearDown" finished-at="2025-08-10T20:08:05 TRT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:05 TRT" name="setUp" finished-at="2025-08-10T20:08:05 TRT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testDeleteUserByUser()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:05 TRT" name="testDeleteUserByUser" description="Delete user by user (self-deletion)" finished-at="2025-08-10T20:08:05 TRT" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 200, but was 400 expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 200, but was 400 expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerDeleteTest.createAndVerifyPlayer(PlayerDeleteTest.java:185)
at api.PlayerDeleteTest.setUp(PlayerDeleteTest.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:578)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteUserByUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:05 TRT" name="tearDown" finished-at="2025-08-10T20:08:05 TRT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:05 TRT" name="setUp" finished-at="2025-08-10T20:08:05 TRT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testUserCannotDeleteAdmin()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:05 TRT" name="testUserCannotDeleteAdmin" description="User cannot delete admin" finished-at="2025-08-10T20:08:05 TRT" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 200, but was 400 expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 200, but was 400 expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerDeleteTest.createAndVerifyPlayer(PlayerDeleteTest.java:185)
at api.PlayerDeleteTest.setUp(PlayerDeleteTest.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:578)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUserCannotDeleteAdmin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerDeleteTest@c262f2f]" started-at="2025-08-10T20:08:05 TRT" name="tearDown" finished-at="2025-08-10T20:08:05 TRT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- api.PlayerDeleteTest -->
      <class name="api.PlayerCreateTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:56 TRT" name="setUp" finished-at="2025-08-10T20:07:56 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithAdminRole()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:56 TRT" name="testCreatePlayerWithAdminRole" description="Create player with admin role" finished-at="2025-08-10T20:07:56 TRT" duration-ms="112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithAdminRole -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:56 TRT" name="tearDown" finished-at="2025-08-10T20:07:56 TRT" duration-ms="97" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:56 TRT" name="setUp" finished-at="2025-08-10T20:07:56 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithInvalidAgeTooOld()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:56 TRT" name="testCreatePlayerWithInvalidAgeTooOld" description="Create player with invalid age (too old - 61)" finished-at="2025-08-10T20:07:56 TRT" duration-ms="98" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Response body is empty; cannot map to ErrorBody]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithInvalidAgeTooOld(PlayerCreateTest.java:125)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithInvalidAgeTooOld -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:56 TRT" name="tearDown" finished-at="2025-08-10T20:07:56 TRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:56 TRT" name="setUp" finished-at="2025-08-10T20:07:56 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithInvalidAgeTooYoung()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:56 TRT" name="testCreatePlayerWithInvalidAgeTooYoung" description="Create player with invalid age (too young - 15)" finished-at="2025-08-10T20:07:56 TRT" duration-ms="89" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Response body is empty; cannot map to ErrorBody]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithInvalidAgeTooYoung(PlayerCreateTest.java:115)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithInvalidAgeTooYoung -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:56 TRT" name="tearDown" finished-at="2025-08-10T20:07:56 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:56 TRT" name="setUp" finished-at="2025-08-10T20:07:56 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithInvalidGender()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:56 TRT" name="testCreatePlayerWithInvalidGender" description="Create player with invalid gender" finished-at="2025-08-10T20:07:57 TRT" duration-ms="91" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User should not be created. expected [400] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User should not be created. expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:271)
at api.PlayerCreateTest.testCreatePlayerWithInvalidGender(PlayerCreateTest.java:137)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithInvalidGender -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="tearDown" finished-at="2025-08-10T20:07:57 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="setUp" finished-at="2025-08-10T20:07:57 TRT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithInvalidPasswordNoLetters()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="testCreatePlayerWithInvalidPasswordNoLetters" description="Create player with invalid password (no letters)" finished-at="2025-08-10T20:07:57 TRT" duration-ms="94" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User should not be created. expected [400] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User should not be created. expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:271)
at api.PlayerCreateTest.testCreatePlayerWithInvalidPasswordNoLetters(PlayerCreateTest.java:179)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithInvalidPasswordNoLetters -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="tearDown" finished-at="2025-08-10T20:07:57 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="setUp" finished-at="2025-08-10T20:07:57 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithInvalidPasswordNoNumbers()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="testCreatePlayerWithInvalidPasswordNoNumbers" description="Create player with invalid password (no numbers)" finished-at="2025-08-10T20:07:57 TRT" duration-ms="89" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User should not be created. expected [400] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User should not be created. expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:271)
at api.PlayerCreateTest.testCreatePlayerWithInvalidPasswordNoNumbers(PlayerCreateTest.java:169)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithInvalidPasswordNoNumbers -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="tearDown" finished-at="2025-08-10T20:07:57 TRT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="setUp" finished-at="2025-08-10T20:07:57 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithInvalidPasswordTooLong()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="testCreatePlayerWithInvalidPasswordTooLong" description="Create player with invalid password (too long)" finished-at="2025-08-10T20:07:57 TRT" duration-ms="86" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User should not be created. expected [400] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User should not be created. expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:271)
at api.PlayerCreateTest.testCreatePlayerWithInvalidPasswordTooLong(PlayerCreateTest.java:159)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithInvalidPasswordTooLong -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="tearDown" finished-at="2025-08-10T20:07:57 TRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="setUp" finished-at="2025-08-10T20:07:57 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithInvalidPasswordTooShort()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="testCreatePlayerWithInvalidPasswordTooShort" description="Create player with invalid password (too short)" finished-at="2025-08-10T20:07:57 TRT" duration-ms="86" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User should not be created. expected [400] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User should not be created. expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:271)
at api.PlayerCreateTest.testCreatePlayerWithInvalidPasswordTooShort(PlayerCreateTest.java:149)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithInvalidPasswordTooShort -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="tearDown" finished-at="2025-08-10T20:07:57 TRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="setUp" finished-at="2025-08-10T20:07:57 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithInvalidRole()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="testCreatePlayerWithInvalidRole" description="Create player with invalid role" finished-at="2025-08-10T20:07:57 TRT" duration-ms="82" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Response body is empty; cannot map to ErrorBody]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithInvalidRole(PlayerCreateTest.java:190)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithInvalidRole -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="tearDown" finished-at="2025-08-10T20:07:57 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="setUp" finished-at="2025-08-10T20:07:57 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithMissingAge()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="testCreatePlayerWithMissingAge" description="Create player with missing age" finished-at="2025-08-10T20:07:57 TRT" duration-ms="91" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Response body is empty; cannot map to ErrorBody]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithMissingAge(PlayerCreateTest.java:201)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithMissingAge -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="tearDown" finished-at="2025-08-10T20:07:57 TRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="setUp" finished-at="2025-08-10T20:07:57 TRT" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithMissingGender()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="testCreatePlayerWithMissingGender" description="Create player with missing gender" finished-at="2025-08-10T20:07:57 TRT" duration-ms="94" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Response body is empty; cannot map to ErrorBody]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithMissingGender(PlayerCreateTest.java:210)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithMissingGender -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="tearDown" finished-at="2025-08-10T20:07:57 TRT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="setUp" finished-at="2025-08-10T20:07:57 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithMissingLogin()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="testCreatePlayerWithMissingLogin" description="Create player with missing login" finished-at="2025-08-10T20:07:57 TRT" duration-ms="98" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Response body is empty; cannot map to ErrorBody]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithMissingLogin(PlayerCreateTest.java:219)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithMissingLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="tearDown" finished-at="2025-08-10T20:07:57 TRT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:57 TRT" name="setUp" finished-at="2025-08-10T20:07:57 TRT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithMissingRole()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="testCreatePlayerWithMissingRole" description="Create player with missing role" finished-at="2025-08-10T20:07:58 TRT" duration-ms="110" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Response body is empty; cannot map to ErrorBody]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithMissingRole(PlayerCreateTest.java:228)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithMissingRole -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="tearDown" finished-at="2025-08-10T20:07:58 TRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="setUp" finished-at="2025-08-10T20:07:58 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithMissingScreenName()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="testCreatePlayerWithMissingScreenName" description="Create player with missing screenName" finished-at="2025-08-10T20:07:58 TRT" duration-ms="95" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Response body is empty; cannot map to ErrorBody]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithValidationError(PlayerCreateTest.java:272)
at api.PlayerCreateTest.testCreatePlayerWithMissingScreenName(PlayerCreateTest.java:237)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithMissingScreenName -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="tearDown" finished-at="2025-08-10T20:07:58 TRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="setUp" finished-at="2025-08-10T20:07:58 TRT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithNonExistentEditor()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="testCreatePlayerWithNonExistentEditor" description="Create player with non-existent editor" finished-at="2025-08-10T20:07:58 TRT" duration-ms="92" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Response body is empty; cannot map to ErrorBody]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateTest.assertCreatePlayerWithAuthorizationError(PlayerCreateTest.java:282)
at api.PlayerCreateTest.testCreatePlayerWithNonExistentEditor(PlayerCreateTest.java:248)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithNonExistentEditor -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="tearDown" finished-at="2025-08-10T20:07:58 TRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="setUp" finished-at="2025-08-10T20:07:58 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithUserRole()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="testCreatePlayerWithUserRole" description="Create player with user role" finished-at="2025-08-10T20:07:58 TRT" duration-ms="92" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithUserRole -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="tearDown" finished-at="2025-08-10T20:07:58 TRT" duration-ms="89" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="setUp" finished-at="2025-08-10T20:07:58 TRT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithValidDataUsingAdmin()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="testCreatePlayerWithValidDataUsingAdmin" description="Create player with valid data using admin" finished-at="2025-08-10T20:07:58 TRT" duration-ms="103" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Wrong age expected [53] but found [null],
Wrong gender expected [female] but found [null],
Wrong password expected [TX2V6JVe084J3b] but found [null],
Wrong role expected [user] but found [null],
Wrong screen_name expected [04a0c6d8] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Wrong age expected [53] but found [null],
Wrong gender expected [female] but found [null],
Wrong password expected [TX2V6JVe084J3b] but found [null],
Wrong role expected [user] but found [null],
Wrong screen_name expected [04a0c6d8] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at api.PlayerCreateTest.assertPlayerEquals(PlayerCreateTest.java:296)
at api.PlayerCreateTest.testCreatePlayerWithValidDataUsingAdmin(PlayerCreateTest.java:74)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithValidDataUsingAdmin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="tearDown" finished-at="2025-08-10T20:07:58 TRT" duration-ms="98" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="setUp" finished-at="2025-08-10T20:07:58 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithValidDataUsingSupervisor()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="testCreatePlayerWithValidDataUsingSupervisor" description="Create player with valid data using supervisor" finished-at="2025-08-10T20:07:58 TRT" duration-ms="87" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Wrong age expected [49] but found [null],
Wrong gender expected [female] but found [null],
Wrong password expected [YWN5mPg2diT3mOc] but found [null],
Wrong role expected [user] but found [null],
Wrong screen_name expected [987ac94d] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Wrong age expected [49] but found [null],
Wrong gender expected [female] but found [null],
Wrong password expected [YWN5mPg2diT3mOc] but found [null],
Wrong role expected [user] but found [null],
Wrong screen_name expected [987ac94d] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at api.PlayerCreateTest.assertPlayerEquals(PlayerCreateTest.java:296)
at api.PlayerCreateTest.testCreatePlayerWithValidDataUsingSupervisor(PlayerCreateTest.java:61)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithValidDataUsingSupervisor -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateTest@45d389f2]" started-at="2025-08-10T20:07:58 TRT" name="tearDown" finished-at="2025-08-10T20:07:59 TRT" duration-ms="82" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- api.PlayerCreateTest -->
      <class name="api.PlayerCreateDuplicateNegativeTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateDuplicateNegativeTest@322b09da]" started-at="2025-08-10T20:07:55 TRT" name="setUp" finished-at="2025-08-10T20:07:55 TRT" duration-ms="99" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithDuplicateLogin()[pri:0, instance:api.PlayerCreateDuplicateNegativeTest@322b09da]" started-at="2025-08-10T20:07:55 TRT" name="testCreatePlayerWithDuplicateLogin" description="Create player with duplicate login" finished-at="2025-08-10T20:07:55 TRT" duration-ms="106" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 403, but was 200 expected [403] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 403, but was 200 expected [403] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerCreateDuplicateNegativeTest.assertCreatePlayerWithValidationError(PlayerCreateDuplicateNegativeTest.java:92)
at api.PlayerCreateDuplicateNegativeTest.testCreatePlayerWithDuplicateLogin(PlayerCreateDuplicateNegativeTest.java:61)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithDuplicateLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateDuplicateNegativeTest@322b09da]" started-at="2025-08-10T20:07:55 TRT" name="tearDown" finished-at="2025-08-10T20:07:55 TRT" duration-ms="218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateDuplicateNegativeTest@322b09da]" started-at="2025-08-10T20:07:55 TRT" name="setUp" finished-at="2025-08-10T20:07:56 TRT" duration-ms="144" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithDuplicateScreenName()[pri:0, instance:api.PlayerCreateDuplicateNegativeTest@322b09da]" started-at="2025-08-10T20:07:56 TRT" name="testCreatePlayerWithDuplicateScreenName" description="Create player with duplicate screenName" finished-at="2025-08-10T20:07:56 TRT" duration-ms="112" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 403, but was 200 expected [403] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 403, but was 200 expected [403] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerCreateDuplicateNegativeTest.assertCreatePlayerWithValidationError(PlayerCreateDuplicateNegativeTest.java:92)
at api.PlayerCreateDuplicateNegativeTest.testCreatePlayerWithDuplicateScreenName(PlayerCreateDuplicateNegativeTest.java:69)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithDuplicateScreenName -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateDuplicateNegativeTest@322b09da]" started-at="2025-08-10T20:07:56 TRT" name="tearDown" finished-at="2025-08-10T20:07:56 TRT" duration-ms="191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- api.PlayerCreateDuplicateNegativeTest -->
      <class name="api.PlayerAdminEditorTest">
        <test-method is-config="true" signature="globalSetup()[pri:0, instance:api.PlayerAdminEditorTest@2b3f7704]" started-at="2025-08-10T20:07:46 TRT" name="globalSetup" finished-at="2025-08-10T20:07:46 TRT" duration-ms="61" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- globalSetup -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerAdminEditorTest@2b3f7704]" started-at="2025-08-10T20:07:46 TRT" name="setUp" finished-at="2025-08-10T20:07:53 TRT" duration-ms="7323" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerAdminEditorTest@2b3f7704]" started-at="2025-08-10T20:07:46 TRT" name="setUp" finished-at="2025-08-10T20:07:53 TRT" duration-ms="7315" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testAdminCanUpdateOtherAdmins()[pri:0, instance:api.PlayerAdminEditorTest@2b3f7704]" started-at="2025-08-10T20:07:53 TRT" name="testAdminCanUpdateOtherAdmins" description="Admin can update other admins" finished-at="2025-08-10T20:07:54 TRT" duration-ms="429" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Response body is empty; cannot map to PlayerResponse]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to PlayerResponse
at api.client.ResponseWrapper.readEntity(ResponseWrapper.java:36)
at api.PlayerAdminEditorTest.verifyPlayerFieldUpdate(PlayerAdminEditorTest.java:112)
at api.PlayerAdminEditorTest.testAdminCanUpdateOtherAdmins(PlayerAdminEditorTest.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAdminCanUpdateOtherAdmins -->
        <test-method signature="testAdminCanDeleteOtherAdmins()[pri:0, instance:api.PlayerAdminEditorTest@2b3f7704]" started-at="2025-08-10T20:07:53 TRT" name="testAdminCanDeleteOtherAdmins" description="Admin can delete other admins" finished-at="2025-08-10T20:07:54 TRT" duration-ms="497" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 404, but was 200 expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 404, but was 200 expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerAdminEditorTest.verifyPlayerDeletion(PlayerAdminEditorTest.java:140)
at api.PlayerAdminEditorTest.testAdminCanDeleteOtherAdmins(PlayerAdminEditorTest.java:89)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAdminCanDeleteOtherAdmins -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerAdminEditorTest@2b3f7704]" started-at="2025-08-10T20:07:54 TRT" name="tearDown" finished-at="2025-08-10T20:07:55 TRT" duration-ms="976" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerAdminEditorTest@2b3f7704]" started-at="2025-08-10T20:07:54 TRT" name="tearDown" finished-at="2025-08-10T20:07:55 TRT" duration-ms="1022" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- api.PlayerAdminEditorTest -->
      <class name="api.PlayerUpdateTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:07 TRT" name="setUp" finished-at="2025-08-10T20:08:07 TRT" duration-ms="83" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:07 TRT" name="setUp" finished-at="2025-08-10T20:08:07 TRT" duration-ms="99" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testUpdateMultipleFields()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:07 TRT" name="testUpdateMultipleFields" description="Update multiple fields at once" finished-at="2025-08-10T20:08:07 TRT" duration-ms="100" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 200, but was 409 expected [200] but found [409]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 200, but was 409 expected [200] but found [409]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerUpdateTest.testUpdateMultipleFields(PlayerUpdateTest.java:149)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateMultipleFields -->
        <test-method signature="testUpdateNonExistentPlayer()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:07 TRT" name="testUpdateNonExistentPlayer" description="Update non-existent player" finished-at="2025-08-10T20:08:07 TRT" duration-ms="104" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 404, but was 200 expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 404, but was 200 expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerUpdateTest.assertUpdatePlayerWithAuthorizationError(PlayerUpdateTest.java:311)
at api.PlayerUpdateTest.testUpdateNonExistentPlayer(PlayerUpdateTest.java:204)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateNonExistentPlayer -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:07 TRT" name="tearDown" finished-at="2025-08-10T20:08:07 TRT" duration-ms="368" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:07 TRT" name="tearDown" finished-at="2025-08-10T20:08:07 TRT" duration-ms="337" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:07 TRT" name="setUp" finished-at="2025-08-10T20:08:08 TRT" duration-ms="84" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:08 TRT" name="setUp" finished-at="2025-08-10T20:08:08 TRT" duration-ms="83" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testUpdatePlayerAge()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:08 TRT" name="testUpdatePlayerAge" description="Update player age" finished-at="2025-08-10T20:08:18 TRT" duration-ms="10174" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Age should be updated correctly expected [30] but found [47]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Age should be updated correctly expected [30] but found [47]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at api.PlayerUpdateTest.verifyPlayerFieldUpdate(PlayerUpdateTest.java:277)
at api.PlayerUpdateTest.testUpdatePlayerAge(PlayerUpdateTest.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdatePlayerAge -->
        <test-method signature="testUpdatePlayerGender()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:08 TRT" name="testUpdatePlayerGender" description="Update player gender" finished-at="2025-08-10T20:08:18 TRT" duration-ms="10164" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdatePlayerGender -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:16 TRT" name="setUp" finished-at="2025-08-10T20:08:17 TRT" duration-ms="73" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testUpdatePlayerLogin()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:17 TRT" name="testUpdatePlayerLogin" description="Update player login" finished-at="2025-08-10T20:08:17 TRT" duration-ms="163" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdatePlayerLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:17 TRT" name="tearDown" finished-at="2025-08-10T20:08:17 TRT" duration-ms="159" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:17 TRT" name="setUp" finished-at="2025-08-10T20:08:17 TRT" duration-ms="83" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testUpdatePlayerPassword()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:17 TRT" name="testUpdatePlayerPassword" description="Update player password" finished-at="2025-08-10T20:08:27 TRT" duration-ms="10165" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdatePlayerPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:18 TRT" name="tearDown" finished-at="2025-08-10T20:08:18 TRT" duration-ms="144" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:18 TRT" name="tearDown" finished-at="2025-08-10T20:08:18 TRT" duration-ms="154" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:18 TRT" name="setUp" finished-at="2025-08-10T20:08:18 TRT" duration-ms="99" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:18 TRT" name="setUp" finished-at="2025-08-10T20:08:18 TRT" duration-ms="130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testUpdatePlayerScreenName()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:18 TRT" name="testUpdatePlayerScreenName" description="Update player screenName" finished-at="2025-08-10T20:08:28 TRT" duration-ms="10179" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ScreenName should be updated correctly expected [bf7ed155] but found [de2d1a83]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ScreenName should be updated correctly expected [bf7ed155] but found [de2d1a83]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at api.PlayerUpdateTest.verifyPlayerFieldUpdate(PlayerUpdateTest.java:289)
at api.PlayerUpdateTest.testUpdatePlayerScreenName(PlayerUpdateTest.java:119)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdatePlayerScreenName -->
        <test-method signature="testUpdatePlayerWithAdminEditor()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:18 TRT" name="testUpdatePlayerWithAdminEditor" description="Update player with admin editor" finished-at="2025-08-10T20:08:28 TRT" duration-ms="10185" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdatePlayerWithAdminEditor -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:27 TRT" name="tearDown" finished-at="2025-08-10T20:08:27 TRT" duration-ms="312" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:27 TRT" name="setUp" finished-at="2025-08-10T20:08:28 TRT" duration-ms="81" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testUpdatePlayerWithInvalidAge()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="testUpdatePlayerWithInvalidAge" description="Update player with invalid age" finished-at="2025-08-10T20:08:28 TRT" duration-ms="87" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 403, but was 200 expected [403] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 403, but was 200 expected [403] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerUpdateTest.assertUpdatePlayerWithValidationError(PlayerUpdateTest.java:301)
at api.PlayerUpdateTest.testUpdatePlayerWithInvalidAge(PlayerUpdateTest.java:172)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdatePlayerWithInvalidAge -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="tearDown" finished-at="2025-08-10T20:08:28 TRT" duration-ms="162" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="setUp" finished-at="2025-08-10T20:08:28 TRT" duration-ms="78" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testUpdatePlayerWithInvalidGender()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="testUpdatePlayerWithInvalidGender" description="Update player with invalid gender" finished-at="2025-08-10T20:08:28 TRT" duration-ms="82" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 400, but was 200 expected [400] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 400, but was 200 expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerUpdateTest.assertUpdatePlayerWithValidationError(PlayerUpdateTest.java:301)
at api.PlayerUpdateTest.testUpdatePlayerWithInvalidGender(PlayerUpdateTest.java:182)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdatePlayerWithInvalidGender -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="tearDown" finished-at="2025-08-10T20:08:28 TRT" duration-ms="158" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="setUp" finished-at="2025-08-10T20:08:28 TRT" duration-ms="83" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User should be created. expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User should be created. expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerUpdateTest.createAndVerifyPlayer(PlayerUpdateTest.java:258)
at api.PlayerUpdateTest.setUp(PlayerUpdateTest.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:578)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="tearDown" finished-at="2025-08-10T20:08:28 TRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="setUp" finished-at="2025-08-10T20:08:28 TRT" duration-ms="96" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User should be created. expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User should be created. expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerUpdateTest.createAndVerifyPlayer(PlayerUpdateTest.java:258)
at api.PlayerUpdateTest.setUp(PlayerUpdateTest.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:578)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testUpdatePlayerWithInvalidPassword()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="testUpdatePlayerWithInvalidPassword" description="Update player with invalid password" finished-at="2025-08-10T20:08:28 TRT" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User should be created. expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User should be created. expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerUpdateTest.createAndVerifyPlayer(PlayerUpdateTest.java:258)
at api.PlayerUpdateTest.setUp(PlayerUpdateTest.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:578)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdatePlayerWithInvalidPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="tearDown" finished-at="2025-08-10T20:08:28 TRT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="setUp" finished-at="2025-08-10T20:08:28 TRT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="tearDown" finished-at="2025-08-10T20:08:28 TRT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="testUserCanUpdateOwnProfile()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="testUserCanUpdateOwnProfile" description="User can update their own profile" finished-at="2025-08-10T20:08:28 TRT" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User should be created. expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User should be created. expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerUpdateTest.createAndVerifyPlayer(PlayerUpdateTest.java:258)
at api.PlayerUpdateTest.setUp(PlayerUpdateTest.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:578)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUserCanUpdateOwnProfile -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="tearDown" finished-at="2025-08-10T20:08:28 TRT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="testUpdatePlayerWithNonExistentEditor()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="testUpdatePlayerWithNonExistentEditor" description="Update player with non-existent editor" finished-at="2025-08-10T20:08:28 TRT" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User should be created. expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User should be created. expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerUpdateTest.createAndVerifyPlayer(PlayerUpdateTest.java:258)
at api.PlayerUpdateTest.setUp(PlayerUpdateTest.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:578)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdatePlayerWithNonExistentEditor -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerUpdateTest@11148dc2]" started-at="2025-08-10T20:08:28 TRT" name="tearDown" finished-at="2025-08-10T20:08:28 TRT" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- api.PlayerUpdateTest -->
      <class name="api.PlayerControllerTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerControllerTest@340c5fb6]" started-at="2025-08-10T20:07:46 TRT" name="setUp" finished-at="2025-08-10T20:07:48 TRT" duration-ms="1964" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCompletePlayerLifecycle()[pri:0, instance:api.PlayerControllerTest@340c5fb6]" started-at="2025-08-10T20:07:48 TRT" name="testCompletePlayerLifecycle" description="Complete player lifecycle: Create -&gt; Get -&gt; Update -&gt; Delete" finished-at="2025-08-10T20:07:54 TRT" duration-ms="5796" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 404, but was 200 expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 404, but was 200 expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerControllerTest.testCompletePlayerLifecycle(PlayerControllerTest.java:113)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCompletePlayerLifecycle -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerControllerTest@340c5fb6]" started-at="2025-08-10T20:07:54 TRT" name="tearDown" finished-at="2025-08-10T20:07:54 TRT" duration-ms="125" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerControllerTest@340c5fb6]" started-at="2025-08-10T20:07:54 TRT" name="setUp" finished-at="2025-08-10T20:07:54 TRT" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testDataConsistencyWorkflow()[pri:0, instance:api.PlayerControllerTest@340c5fb6]" started-at="2025-08-10T20:07:54 TRT" name="testDataConsistencyWorkflow" description="Data consistency workflow: Verify data integrity across operations" finished-at="2025-08-10T20:08:05 TRT" duration-ms="10988" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDataConsistencyWorkflow -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerControllerTest@340c5fb6]" started-at="2025-08-10T20:07:55 TRT" name="setUp" finished-at="2025-08-10T20:07:55 TRT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testMultiUserWorkflow()[pri:0, instance:api.PlayerControllerTest@340c5fb6]" started-at="2025-08-10T20:07:55 TRT" name="testMultiUserWorkflow" description="Multi-user workflow: Create multiple users and verify isolation" finished-at="2025-08-10T20:08:06 TRT" duration-ms="10671" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Users should have different screen names did not expect [null] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Users should have different screen names did not expect [null] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at api.PlayerControllerTest.testMultiUserWorkflow(PlayerControllerTest.java:168)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMultiUserWorkflow -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerControllerTest@340c5fb6]" started-at="2025-08-10T20:08:05 TRT" name="tearDown" finished-at="2025-08-10T20:08:06 TRT" duration-ms="315" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerControllerTest@340c5fb6]" started-at="2025-08-10T20:08:06 TRT" name="tearDown" finished-at="2025-08-10T20:08:06 TRT" duration-ms="307" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- api.PlayerControllerTest -->
      <class name="api.PlayerCreateWithUserEditorNegativeTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateWithUserEditorNegativeTest@66298fe9]" started-at="2025-08-10T20:07:59 TRT" name="setUp" finished-at="2025-08-10T20:07:59 TRT" duration-ms="98" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCreatePlayerWithUserEditor()[pri:0, instance:api.PlayerCreateWithUserEditorNegativeTest@66298fe9]" started-at="2025-08-10T20:07:59 TRT" name="testCreatePlayerWithUserEditor" description="Create player with user editor (unauthorized)" finished-at="2025-08-10T20:07:59 TRT" duration-ms="93" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Response body is empty; cannot map to ErrorBody]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateWithUserEditorNegativeTest.assertCreatePlayerWithAuthorizationError(PlayerCreateWithUserEditorNegativeTest.java:96)
at api.PlayerCreateWithUserEditorNegativeTest.testCreatePlayerWithUserEditor(PlayerCreateWithUserEditorNegativeTest.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePlayerWithUserEditor -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateWithUserEditorNegativeTest@66298fe9]" started-at="2025-08-10T20:07:59 TRT" name="tearDown" finished-at="2025-08-10T20:07:59 TRT" duration-ms="200" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateWithUserEditorNegativeTest@66298fe9]" started-at="2025-08-10T20:07:59 TRT" name="setUp" finished-at="2025-08-10T20:07:59 TRT" duration-ms="88" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testUserCannotAccessAdminOperations()[pri:0, instance:api.PlayerCreateWithUserEditorNegativeTest@66298fe9]" started-at="2025-08-10T20:07:59 TRT" name="testUserCannotAccessAdminOperations" description="User cannot access admin operations" finished-at="2025-08-10T20:08:00 TRT" duration-ms="90" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Response body is empty; cannot map to ErrorBody]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Response body is empty; cannot map to ErrorBody
at api.client.ResponseWrapper.readError(ResponseWrapper.java:56)
at api.PlayerCreateWithUserEditorNegativeTest.assertCreatePlayerWithAuthorizationError(PlayerCreateWithUserEditorNegativeTest.java:96)
at api.PlayerCreateWithUserEditorNegativeTest.testUserCannotAccessAdminOperations(PlayerCreateWithUserEditorNegativeTest.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUserCannotAccessAdminOperations -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateWithUserEditorNegativeTest@66298fe9]" started-at="2025-08-10T20:08:00 TRT" name="tearDown" finished-at="2025-08-10T20:08:00 TRT" duration-ms="183" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- api.PlayerCreateWithUserEditorNegativeTest -->
      <class name="api.PlayerUserEditorNegativeTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerUserEditorNegativeTest@3be80ece]" started-at="2025-08-10T20:08:28 TRT" name="setUp" finished-at="2025-08-10T20:08:28 TRT" duration-ms="210" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerUserEditorNegativeTest@3be80ece]" started-at="2025-08-10T20:08:28 TRT" name="setUp" finished-at="2025-08-10T20:08:29 TRT" duration-ms="203" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testUpdatePlayerWithUserEditor()[pri:0, instance:api.PlayerUserEditorNegativeTest@3be80ece]" started-at="2025-08-10T20:08:29 TRT" name="testUpdatePlayerWithUserEditor" description="Update player with user editor (unauthorized)" finished-at="2025-08-10T20:08:29 TRT" duration-ms="85" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 403, but was 200 expected [403] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 403, but was 200 expected [403] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerUserEditorNegativeTest.assertUpdatePlayerWithAuthorizationError(PlayerUserEditorNegativeTest.java:107)
at api.PlayerUserEditorNegativeTest.testUpdatePlayerWithUserEditor(PlayerUserEditorNegativeTest.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdatePlayerWithUserEditor -->
        <test-method signature="testUserCannotDeleteOtherUsers()[pri:0, instance:api.PlayerUserEditorNegativeTest@3be80ece]" started-at="2025-08-10T20:08:29 TRT" name="testUserCannotDeleteOtherUsers" description="User cannot delete other users" finished-at="2025-08-10T20:08:29 TRT" duration-ms="91" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status code should be 403 when user tries to delete another user expected [403] but found [204]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status code should be 403 when user tries to delete another user expected [403] but found [204]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.PlayerUserEditorNegativeTest.testUserCannotDeleteOtherUsers(PlayerUserEditorNegativeTest.java:84)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUserCannotDeleteOtherUsers -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerUserEditorNegativeTest@3be80ece]" started-at="2025-08-10T20:08:29 TRT" name="tearDown" finished-at="2025-08-10T20:08:29 TRT" duration-ms="663" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerUserEditorNegativeTest@3be80ece]" started-at="2025-08-10T20:08:29 TRT" name="tearDown" finished-at="2025-08-10T20:08:29 TRT" duration-ms="687" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- api.PlayerUserEditorNegativeTest -->
      <class name="api.PlayerCreateWithAdminEditorNegativeTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerCreateWithAdminEditorNegativeTest@308e87a1]" started-at="2025-08-10T20:07:59 TRT" name="setUp" finished-at="2025-08-10T20:07:59 TRT" duration-ms="88" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testAdminCannotCreateSupervisor()[pri:0, instance:api.PlayerCreateWithAdminEditorNegativeTest@308e87a1]" started-at="2025-08-10T20:07:59 TRT" name="testAdminCannotCreateSupervisor" description="Admin cannot create supervisor" finished-at="2025-08-10T20:07:59 TRT" duration-ms="98" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 403, but was 400 expected [403] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 403, but was 400 expected [403] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerCreateWithAdminEditorNegativeTest.assertCreatePlayerWithAuthorizationError(PlayerCreateWithAdminEditorNegativeTest.java:89)
at api.PlayerCreateWithAdminEditorNegativeTest.testAdminCannotCreateSupervisor(PlayerCreateWithAdminEditorNegativeTest.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAdminCannotCreateSupervisor -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerCreateWithAdminEditorNegativeTest@308e87a1]" started-at="2025-08-10T20:07:59 TRT" name="tearDown" finished-at="2025-08-10T20:07:59 TRT" duration-ms="194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- api.PlayerCreateWithAdminEditorNegativeTest -->
      <class name="api.PlayerGetTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerGetTest@5563bb40]" started-at="2025-08-10T20:08:05 TRT" name="setUp" finished-at="2025-08-10T20:08:05 TRT" duration-ms="84" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testGetAllPlayers()[pri:0, instance:api.PlayerGetTest@5563bb40]" started-at="2025-08-10T20:08:05 TRT" name="testGetAllPlayers" description="Get all players" finished-at="2025-08-10T20:08:07 TRT" duration-ms="1600" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetAllPlayers -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerGetTest@5563bb40]" started-at="2025-08-10T20:08:06 TRT" name="setUp" finished-at="2025-08-10T20:08:06 TRT" duration-ms="92" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testGetPlayerAfterCreation()[pri:0, instance:api.PlayerGetTest@5563bb40]" started-at="2025-08-10T20:08:06 TRT" name="testGetPlayerAfterCreation" description="Get player after creation and verify all fields" finished-at="2025-08-10T20:08:06 TRT" duration-ms="96" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Age should match expected [47] but found [24],
Gender should match expected [female] but found [male],
Login should match expected [dana.pfannerstill] but found [gail.wehner],
Password should match expected [6591ee1FpI2N8W9] but found [SZi1lC78ywAeMi],
ScreenName should match expected [c87c109c] but found [91ad93a9]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Age should match expected [47] but found [24],
Gender should match expected [female] but found [male],
Login should match expected [dana.pfannerstill] but found [gail.wehner],
Password should match expected [6591ee1FpI2N8W9] but found [SZi1lC78ywAeMi],
ScreenName should match expected [c87c109c] but found [91ad93a9]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at api.PlayerGetTest.testGetPlayerAfterCreation(PlayerGetTest.java:108)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetPlayerAfterCreation -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerGetTest@5563bb40]" started-at="2025-08-10T20:08:06 TRT" name="setUp" finished-at="2025-08-10T20:08:06 TRT" duration-ms="104" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerGetTest@5563bb40]" started-at="2025-08-10T20:08:06 TRT" name="tearDown" finished-at="2025-08-10T20:08:06 TRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerGetTest@5563bb40]" started-at="2025-08-10T20:08:06 TRT" name="setUp" finished-at="2025-08-10T20:08:06 TRT" duration-ms="104" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testGetPlayerByNonExistentId()[pri:0, instance:api.PlayerGetTest@5563bb40]" started-at="2025-08-10T20:08:06 TRT" name="testGetPlayerByNonExistentId" description="Get player by non-existent ID" finished-at="2025-08-10T20:08:06 TRT" duration-ms="93" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 404, but was 200 expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 404, but was 200 expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerGetTest.testGetPlayerByNonExistentId(PlayerGetTest.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetPlayerByNonExistentId -->
        <test-method signature="testGetPlayerWithBoundaryIds()[pri:0, instance:api.PlayerGetTest@5563bb40]" started-at="2025-08-10T20:08:06 TRT" name="testGetPlayerWithBoundaryIds" description="Get player with boundary ID values" finished-at="2025-08-10T20:08:16 TRT" duration-ms="10166" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 400, but was 200 expected [400] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 400, but was 200 expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerGetTest.testGetPlayerWithBoundaryIds(PlayerGetTest.java:129)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetPlayerWithBoundaryIds -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerGetTest@5563bb40]" started-at="2025-08-10T20:08:06 TRT" name="tearDown" finished-at="2025-08-10T20:08:07 TRT" duration-ms="404" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerGetTest@5563bb40]" started-at="2025-08-10T20:08:07 TRT" name="tearDown" finished-at="2025-08-10T20:08:07 TRT" duration-ms="361" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.PlayerGetTest@5563bb40]" started-at="2025-08-10T20:08:07 TRT" name="setUp" finished-at="2025-08-10T20:08:07 TRT" duration-ms="93" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testGetPlayerWithNullId()[pri:0, instance:api.PlayerGetTest@5563bb40]" started-at="2025-08-10T20:08:07 TRT" name="testGetPlayerWithNullId" description="Get player with null playerId" finished-at="2025-08-10T20:08:07 TRT" duration-ms="90" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected HTTP status code 400, but was 200 expected [400] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected HTTP status code 400, but was 200 expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.client.ResponseWrapper.expectingStatusCode(ResponseWrapper.java:49)
at api.PlayerGetTest.testGetPlayerWithNullId(PlayerGetTest.java:86)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetPlayerWithNullId -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerGetTest@5563bb40]" started-at="2025-08-10T20:08:07 TRT" name="tearDown" finished-at="2025-08-10T20:08:07 TRT" duration-ms="161" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:api.PlayerGetTest@5563bb40]" started-at="2025-08-10T20:08:16 TRT" name="tearDown" finished-at="2025-08-10T20:08:16 TRT" duration-ms="149" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- api.PlayerGetTest -->
    </test> <!-- Player Controller Tests -->
  </suite> <!-- Player Controller Test Suite -->
</testng-results>
